import java.util.*;  
import java.util.stream.Collectors;  
import org.apache.commons.lang3.RandomStringUtils;  
  
public class passwordgenerator  {  
       public static String generateSecurePassword() {    
        String numbersStr = RandomStringUtils.randomNumeric(2);  
        String specialCharStr = RandomStringUtils.random(2, 33, 47, false, false);    
        String totalCharsStr = RandomStringUtils.randomAlphanumeric(2); 
        String upperCaseStr = RandomStringUtils.random(2, 65, 90, true, false);  
        String lowerCaseStr = RandomStringUtils.random(2, 97, 122, true, false);  
        
        String demoPassword = upperCaseStr.concat(lowerCaseStr).concat(numbersStr)
                                          .concat(specialCharStr).concat(totalCharsStr); 
        List<Character> listOfChar = demoPassword.chars().mapToObj(data -> (char) data).collect(Collectors.toList());  
        Collections.shuffle(listOfChar);   
        String password = listOfChar.stream()
                                    .collect(StringBuilder::new, StringBuilder::append, StringBuilder::append)
                                    .toString(); 
        return password;  
    }   
    public static void main(String args[]) {   
        String pass = generateSecurePassword();  
        System.out.println("Password generated by RandomStringUtils class is:"+pass);     
    } 
}  
